//P1789 【Mc生存】插火把
#include<stdio.h>
int main(){
    int n,m,k,i,j,count=0;
    scanf("%d%d%d",&n,&m,&k);
    char c[n][n];
    int a[2*m],b[2*k];
    for(i=0;i<m;i++){
        scanf("%d%d",&a[2*i],&a[2*i+1]);
    } 
    if(k>0){
        for(i=0;i<k;i++){
            scanf("%d%d",&b[2*i],&b[2*i+1]);
        }
    }
    for(i=0;i<n;i++){
        for(j=0;j<n;j++){
            c[i][j]='1';
        }
    }
    for(i=0;i<m;i++){
        c[a[2*i]-1][a[2*i+1]-1]='0';
        if(a[2*i]-3>=0){//up2
            c[a[2*i]-3][a[2*i+1]-1]='0';
        }
        if(a[2*i]-2>=0){//up1
            c[a[2*i]-2][a[2*i+1]-1]='0';
        }
        if(a[2*i]+1<=n-1){//down2
            c[a[2*i]+1][a[2*i+1]-1]='0';
        }
        if(a[2*i]<=n-1){//down1
            c[a[2*i]][a[2*i+1]-1]='0';
        }
        if(a[2*i]-2>=0&&a[2*i+1]-2>=0){//nw
            c[a[2*i]-2][a[2*i+1]-2]='0';
        }
        if(a[2*i]-2>=0&&a[2*i+1]<=n-1){//ne
            c[a[2*i]-2][a[2*i+1]]='0';
        }
        if(a[2*i]<=n-1&&a[2*i+1]-2>=0){//sw
            c[a[2*i]][a[2*i+1]-2]='0';
        }
        if(a[2*i]<=n-1&&a[2*i+1]<=n-1){//se
            c[a[2*i]][a[2*i+1]]='0';
        }
        if(a[2*i+1]-3>=0){//left2
            c[a[2*i]-1][a[2*i+1]-3]='0';
        }
        if(a[2*i+1]-2>=0){//left1
            c[a[2*i]-1][a[2*i+1]-2]='0';
        }
        if(a[2*i+1]+1<=n-1){//right2
            c[a[2*i]-1][a[2*i+1]+1]='0';
        }
        if(a[2*i+1]<=n-1){//right1
            c[a[2*i]-1][a[2*i+1]]='0';
        }
    }
    if(k>0){
        for(i=0;i<k;i++){
            for(j=b[2*i]-3;j<b[2*i]+2;j++){
                for(m=b[2*i+1]-3;m<b[2*i+1]+2;m++){
                    if(j<0||m<0||j>=n||m>=n){
                        continue;
                    }else{
                        c[j][m]='0';
                    }
                }
            }
        } 
    }
    for(i=0;i<n;i++){
        for(j=0;j<n;j++){
            if(c[i][j]=='1'){
                count++;
            }
        }
    }
    printf("%d",count);
    return 0;
}