//P1957 口算练习题
#include<stdio.h>
int main(){
    int n,i,j=0,m,a=0,b=0,c,d=1,count=0,k=0,p=0,flag;
    char s[11],e,r[10000];
    scanf("%d",&n);
    scanf(" %c",&e);
    for(i=0;i<n;i++){
        while(e!='\n'){
            s[j++]=e;
            scanf("%c",&e);
        }
        if(s[0]=='a'){//加
            for(m=2;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='+';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            c=a+b;
            while(c/10!=0){
                count++;
                c/=10;
            }
            c=a+b;
            for(m=0;m<count;m++){
                d*=10;
            }
            for(m=count;m>=0;m--){
                r[k++]=(c/d)+'0';
                c%=d;
                d/=10;
            }
            d=1;
            r[k++]='\n';
            if(j+count<10){
                r[k++]=(j+count)+'0'; 
            }else{
                a=j+count;
                while(a/10!=0){
                    p++;
                    a/=10;
                }
                for(m=0;m<p;m++){
                    d*=10;
                }
                a=j+count;
                for(m=p;m>=0;m--){
                    r[k++]=(a/d)+'0';
                    a%=d;
                    d/=10;
                }
            }
            if(i!=n-1){
                r[k++]='\n'; 
            }
            flag=1;
        }else if(s[0]=='b'){//减
            for(m=2;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='-';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            if(a>=b){
                c=a-b;
                while(c/10!=0){
                    count++;
                    c/=10;
                }
                c=a-b;
                for(m=0;m<count;m++){
                    d*=10;
                }
                for(m=count;m>=0;m--){
                    r[k++]=(c/d)+'0';
                    c%=d;
                    d/=10;
                }
                d=1;
                r[k++]='\n';
                if(j+count<10){
                    r[k++]=(j+count)+'0'; 
                }else{
                    a=j+count;
                    while(a/10!=0){
                        p++;
                        a/=10;
                    }
                    for(m=0;m<p;m++){
                        d*=10;
                    }
                    a=j+count;
                    for(m=p;m>=0;m--){
                        r[k++]=(a/d)+'0';
                        a%=d;
                        d/=10;
                    } 
                }
                if(i!=n-1){
                    r[k++]='\n'; 
                }
                flag=2;
            }else{
                r[k++]='-';
                c=b-a;
                while(c/10!=0){
                    count++;
                    c/=10;
                }
                c=b-a;
                for(m=0;m<count;m++){
                    d*=10;
                }
                for(m=count;m>=0;m--){
                    r[k++]=(c/d)+'0';
                    c%=d;
                    d/=10;
                }
                d=1;
                r[k++]='\n';
                if(j+count+1<10){
                    r[k++]=(j+count+1)+'0'; 
                }else{
                    a=j+count+1;
                    while(a/10!=0){
                        p++;
                        a/=10;
                    }
                    for(m=0;m<p;m++){
                        d*=10;
                    }
                    a=j+count+1;
                    for(m=p;m>=0;m--){
                        r[k++]=(a/d)+'0';
                        a%=d;
                        d/=10;
                    } 
                }
                if(i!=n-1){
                    r[k++]='\n'; 
                }
                flag=2;
            }
        }else if(s[0]=='c'){//乘
            for(m=2;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='*';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            c=a*b;
            while(c/10!=0){
                count++;
                c/=10;
            }
            c=a*b;
            for(m=0;m<count;m++){
                d*=10;
            }
            for(m=count;m>=0;m--){
                r[k++]=(c/d)+'0';
                c%=d;
                d/=10;
            }
            d=1;
            r[k++]='\n';
            if(j+count<10){
                r[k++]=(j+count)+'0'; 
            }else{
                a=j+count;
                while(a/10!=0){
                    p++;
                    a/=10;
                }
                for(m=0;m<p;m++){
                    d*=10;
                }
                a=j+count;
                for(m=p;m>=0;m--){
                    r[k++]=(a/d)+'0';
                    a%=d;
                    d/=10;
                } 
            }
            if(i!=n-1){
                r[k++]='\n'; 
            }
            flag=3;
        }else if(s[0]!='a'&&s[0]!='b'&&s[0]!='c'&&flag==1){
            for(m=0;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='+';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            c=a+b;
            while(c/10!=0){
                count++;
                c/=10;
            }
            c=a+b;
            for(m=0;m<count;m++){
                d*=10;
            }
            for(m=count;m>=0;m--){
                r[k++]=(c/d)+'0';
                c%=d;
                d/=10;
            }
            d=1;
            r[k++]='\n';
            if(j+count+2<10){
                r[k++]=(j+count+2)+'0'; 
            }else{
                a=j+count+2;
                while(a/10!=0){
                    p++;
                    a/=10;
                }
                for(m=0;m<p;m++){
                    d*=10;
                }
                a=j+count+2;
                for(m=p;m>=0;m--){
                    r[k++]=(a/d)+'0';
                    a%=d;
                    d/=10;
                }
            }
            if(i!=n-1){
                r[k++]='\n'; 
            }
        }else if(s[0]!='a'&&s[0]!='b'&&s[0]!='c'&&flag==2){
            for(m=0;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='-';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            if(a>=b){
                c=a-b;
                while(c/10!=0){
                    count++;
                    c/=10;
                }
                c=a-b;
                for(m=0;m<count;m++){
                    d*=10;
                }
                for(m=count;m>=0;m--){
                    r[k++]=(c/d)+'0';
                    c%=d;
                    d/=10;
                }
                d=1;
                r[k++]='\n';
                if(j+count+2<10){
                    r[k++]=(j+count+2)+'0'; 
                }else{
                    a=j+count+2;
                    while(a/10!=0){
                        p++;
                        a/=10;
                    }
                    for(m=0;m<p;m++){
                        d*=10;
                    }
                    a=j+count+2;
                    for(m=p;m>=0;m--){
                        r[k++]=(a/d)+'0';
                        a%=d;
                        d/=10;
                    } 
                }
                if(i!=n-1){
                    r[k++]='\n'; 
                }
                flag=2;
            }else{
                r[k++]='-';
                c=b-a;
                while(c/10!=0){
                    count++;
                    c/=10;
                }
                c=b-a;
                for(m=0;m<count;m++){
                    d*=10;
                }
                for(m=count;m>=0;m--){
                    r[k++]=(c/d)+'0';
                    c%=d;
                    d/=10;
                }
                d=1;
                r[k++]='\n';
                if(j+count+3<10){
                    r[k++]=(j+count+3)+'0'; 
                }else{
                    a=j+count+3;
                    while(a/10!=0){
                        p++;
                        a/=10;
                    }
                    for(m=0;m<p;m++){
                        d*=10;
                    }
                    a=j+count+3;
                    for(m=p;m>=0;m--){
                        r[k++]=(a/d)+'0';
                        a%=d;
                        d/=10;
                    } 
                }
                if(i!=n-1){
                    r[k++]='\n'; 
                }
            }
        }else if(s[0]!='a'&&s[0]!='b'&&s[0]!='c'&&flag==3){
            for(m=0;m<j;m++){
                if(s[m]==' '){
                    a/=10;
                    m++;
                    break;
                }
                r[k++]=s[m];
                a+=(s[m]-'0');
                a*=10;
            }
            r[k++]='*';
            for(;m<j;m++){
                r[k++]=s[m];
                b+=(s[m]-'0');
                b*=10;
            }
            r[k++]='=';
            b/=10;
            c=a*b;
            while(c/10!=0){
                count++;
                c/=10;
            }
            c=a*b;
            for(m=0;m<count;m++){
                d*=10;
            }
            for(m=count;m>=0;m--){
                r[k++]=(c/d)+'0';
                c%=d;
                d/=10;
            }
            d=1;
            r[k++]='\n';
            if(j+count+2<10){
                r[k++]=(j+count+2)+'0'; 
            }else{
                a=j+count+2;
                while(a/10!=0){
                    p++;
                    a/=10;
                }
                for(m=0;m<p;m++){
                    d*=10;
                }
                a=j+count+2;
                for(m=p;m>=0;m--){
                    r[k++]=(a/d)+'0';
                    a%=d;
                    d/=10;
                } 
            }
            if(i!=n-1){
                r[k++]='\n'; 
            }
        }
        a=0;b=0;d=1;j=0;count=0;p=0;
        if(i!=n-1){
            scanf(" %c",&e);
        }
    }
    puts(r);
    return 0;
}